#!/usr/bin/env sh

STAGED_FILES="$(git diff --cached --name-only)"

# Always run biome against staged files
pnpm biome:staged

WORKERS_CHANGED=false
SITE_CHANGED=false

if printf "%s" "$STAGED_FILES" | grep -q '^workers/'; then
  WORKERS_CHANGED=true
fi

if printf "%s" "$STAGED_FILES" | grep -q '^site/'; then
  SITE_CHANGED=true
fi

if [ "$WORKERS_CHANGED" = "true" ] && [ "$SITE_CHANGED" = "true" ]; then
  pnpm typecheck
else
  if [ "$WORKERS_CHANGED" = "true" ]; then
    pnpm typecheck:workers
  fi

  if [ "$SITE_CHANGED" = "true" ]; then
    pnpm typecheck:site
  fi
fi
