#!/usr/bin/env sh

STAGED_FILES="$(git diff --cached --name-only)"

# Always run biome against staged files
pnpm biome:staged

PACKAGES=""

if printf "%s" "$STAGED_FILES" | grep -q '^workers/'; then
  PACKAGES="$PACKAGES workers"
fi

if printf "%s" "$STAGED_FILES" | grep -q '^site/'; then
  PACKAGES="$PACKAGES site"
fi

for pkg in $PACKAGES; do
  pnpm "typecheck:${pkg}"
done
